defaults: &defaults
  adapter: mysql2
  encoding: utf8
  host: 0.0.0.0
  username: root
  password: 

development:
  database: rails3_test
  <<: *defaults

production:
  database: rails3_test
  <<: *defaults

